SET XACT_ABORT ON;

DECLARE @EMPRESA INT = {{ $json.VDNOTAC_EMPRESA === null || $json.VDNOTAC_EMPRESA === undefined || $json.VDNOTAC_EMPRESA === "" ? "NULL" : Number($json.VDNOTAC_EMPRESA) }};
DECLARE @FILIAL INT = {{ $json.VDNOTAC_FILIAL === null || $json.VDNOTAC_FILIAL === undefined || $json.VDNOTAC_FILIAL === "" ? "NULL" : Number($json.VDNOTAC_FILIAL) }};
DECLARE @ENTRADA_SAIDA VARCHAR(1) = '{{ String($json.VDNOTAC_ENTRADA_SAIDA || "E").replaceAll("'", "''") }}';
DECLARE @PESSOA INT = {{ $json.ID_FORNECEDOR === null || $json.ID_FORNECEDOR === undefined || $json.ID_FORNECEDOR === "" ? "NULL" : Number($json.ID_FORNECEDOR) }};
DECLARE @NOTA_FISCAL NUMERIC(18,0) = {{ $json.VDNOTAC_NOTA_FISCAL === null || $json.VDNOTAC_NOTA_FISCAL === undefined || $json.VDNOTAC_NOTA_FISCAL === "" ? "NULL" : Number(String($json.VDNOTAC_NOTA_FISCAL).replace(/\D/g, '') || 0) }};
DECLARE @SERIE VARCHAR(10) = '{{ String($json.VDNOTAC_SERIE || "E").replaceAll("'", "''") }}';
DECLARE @MOVIMENTACAO_FISCAL INT = {{ $json.VDNOTAC_MOVIMENTACAO_FISCAL === null || $json.VDNOTAC_MOVIMENTACAO_FISCAL === undefined || $json.VDNOTAC_MOVIMENTACAO_FISCAL === "" ? "NULL" : Number($json.VDNOTAC_MOVIMENTACAO_FISCAL) }};
DECLARE @DATA_EMISSAO DATETIME = {{ $json.VDNOTAC_DATA_EMISSAO ? "CONVERT(DATETIME, '" + String($json.VDNOTAC_DATA_EMISSAO).substring(0, 10).replaceAll("'", "''") + "', 120)" : "NULL" }};
DECLARE @DT_ENTRADA DATETIME = {{ $json.DECIS_DATA_ENTRADA ? "CONVERT(DATETIME, '" + String($json.DECIS_DATA_ENTRADA).substring(0, 10).replaceAll("'", "''") + "', 120)" : "NULL" }};
DECLARE @USUARIO INT = {{ $json.VDNOTAC_USUARIO_INCLUSAO === null || $json.VDNOTAC_USUARIO_INCLUSAO === undefined || $json.VDNOTAC_USUARIO_INCLUSAO === "" ? "9980" : Number($json.VDNOTAC_USUARIO_INCLUSAO) }};
DECLARE @CNPJ VARCHAR(20) = '{{ String($json.CNPJ_FORNECEDOR_LIMPO || $json.VDNOTAC_CNPJ || "").replaceAll("'", "''") }}';
DECLARE @NOME VARCHAR(100) = LEFT('{{ String($json.VDNOTAC_NOMEPESSOA || $json.FORNECEDOR || "FORNECEDOR NFS-E").replaceAll("'", "''") }}', 100);
DECLARE @MUNICIPIO VARCHAR(40) = LEFT('{{ String($json.VDNOTAC_MUNICIPIO || $json.CIDADE_FORNECEDOR || "").replaceAll("'", "''") }}', 40);
DECLARE @UF VARCHAR(2) = LEFT('{{ String($json.VDNOTAC_UF || $json.UF_FORNECEDOR || "").replaceAll("'", "''") }}', 2);
DECLARE @CODIGO_MUNICIPIO INT = {{ $json.VDNOTAC_CODIGOMUNICIPIO === null || $json.VDNOTAC_CODIGOMUNICIPIO === undefined || $json.VDNOTAC_CODIGOMUNICIPIO === "" ? "NULL" : Number($json.VDNOTAC_CODIGOMUNICIPIO) }};
DECLARE @CODIGO_ACESSO VARCHAR(255) = LEFT('{{ String($json.VDNOTAC_CODIGOACESSO || $json.CHAVE || "").replaceAll("'", "''") }}', 255);
DECLARE @NATUREZA VARCHAR(60) = LEFT('{{ String($json.VDNOTAC_NATUREZA || "Prestacao de Servico").replaceAll("'", "''") }}', 60);
DECLARE @OBSERVACAO VARCHAR(MAX) = '{{ String($json.VDNOTAC_OBSERVACAO || $json.OBSERVACAO || "").replaceAll("'", "''") }}';
DECLARE @DADOS_ADICIONAIS VARCHAR(MAX) = '{{ String($json.VDNOTAC_DADOS_ADICIONAIS || "").replaceAll("'", "''") }}';
DECLARE @DESCRICAO VARCHAR(MAX) = '{{ String($json.VDNOTAS_DESCRICAO || $json.DESCRICAO || "SERVICO NFS-E").replaceAll("'", "''") }}';
DECLARE @MODELO_DOCUMENTO VARCHAR(10) = '{{ String($json.VDNOTAC_MODELODOCUMENTO || "01").replaceAll("'", "''") }}';

DECLARE @VALOR_SERVICO NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_SERVICO || 0) }};
DECLARE @VALOR_TOTAL NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_TOTAL || $json.VALOR || 0) }};
DECLARE @VALOR_DESCONTO NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_DESCONTO || 0) }};
DECLARE @VALOR_ISS NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_ISS || 0) }};
DECLARE @ALIQUOTA_ISS NUMERIC(15,4) = {{ Number($json.VDNOTAC_ALIQUOTA_ISS || 0) }};
DECLARE @VALOR_PIS NUMERIC(15,2) = {{ Number($json.VDNOTAS_VALORPIS || 0) }};
DECLARE @VALOR_COFINS NUMERIC(15,2) = {{ Number($json.VDNOTAS_VALORCOFINS || 0) }};
DECLARE @VALOR_DEDUCAO NUMERIC(15,2) = {{ Number($json.VDNOTAS_VALORDEDUCAO || 0) }};
DECLARE @SERVICO INT = {{ Number($json.VDNOTAS_SERVICO || 0) }};
DECLARE @CODIGO_FEDERAL_SERVICO INT = {{ $json.VDNOTAS_CODIGOFEDERALSERVICO === null || $json.VDNOTAS_CODIGOFEDERALSERVICO === undefined || $json.VDNOTAS_CODIGOFEDERALSERVICO === "" ? "NULL" : Number($json.VDNOTAS_CODIGOFEDERALSERVICO) }};
DECLARE @CODIGO_MUNICIPIO_OCORRENCIA INT = {{ $json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA === null || $json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA === undefined || $json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA === "" ? "NULL" : Number($json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA) }};
DECLARE @NATUREZA_CREDITO INT = {{ Number($json.VDNOTAS_NATUREZACREDITO || 3) }};
DECLARE @CST_COFINS INT = {{ Number($json.VDNOTAS_CSTCOFINS || 74) }};
DECLARE @CST_PIS INT = {{ Number($json.VDNOTAS_CSTPIS || 74) }};
DECLARE @CODIGO_PADRAO INT = {{ $json.VDNOTAS_CODIGOPADRAO === null || $json.VDNOTAS_CODIGOPADRAO === undefined || $json.VDNOTAS_CODIGOPADRAO === "" ? "NULL" : Number($json.VDNOTAS_CODIGOPADRAO) }};
DECLARE @CONTA_CONTABIL INT = {{ $json.VDNOTAS_CONTACONTABIL === null || $json.VDNOTAS_CONTACONTABIL === undefined || $json.VDNOTAS_CONTACONTABIL === "" ? "NULL" : Number($json.VDNOTAS_CONTACONTABIL) }};
DECLARE @CODIGO_PADRAO2 INT = {{ Number($json.VDNOTAS_CODIGOPADRAO2 || 410) }};
DECLARE @CST_CBS INT = {{ Number($json.VDNOTAS_CSTCBS || 410) }};
DECLARE @CST_CLASSIFICACAO_CBS INT = {{ Number($json.VDNOTAS_CSTCLASSIFICACAOCBS || 410999) }};

IF @EMPRESA IS NULL THROW 51000, 'EMPRESA DECIS nao informada.', 1;
IF @FILIAL IS NULL THROW 51001, 'FILIAL DECIS nao localizada pelo CNPJ da empresa. Verifique o CASE de filial na consulta do Hub.', 1;
IF @NOTA_FISCAL IS NULL THROW 51002, 'NUMERO DA NOTA nao informado.', 1;
IF @MOVIMENTACAO_FISCAL IS NULL THROW 51003, 'MOVIMENTACAO FISCAL / CFOP nao informado.', 1;
IF @DT_ENTRADA IS NULL THROW 51004, 'DATA DE ENTRADA DECIS nao informada.', 1;
IF @CNPJ = '' THROW 51005, 'CNPJ DO FORNECEDOR nao informado.', 1;

BEGIN TRAN;

IF @PESSOA IS NULL
BEGIN
  SELECT @PESSOA = ISNULL(MAX(PESSOA), 0) + 1
  FROM CGPESSOA WITH (UPDLOCK, HOLDLOCK);

  INSERT INTO CGPESSOA (
    PESSOA, NOME, EMPRESA, ESTADO, FISICO_JURIDICO, FILIAL,
    DATA_ALTERACAO, USUARIO_ALTERACAO, SENHA, DataHoraInclusao,
    UsuarioInclusao, TipoEmpresa
  )
  VALUES (
    @PESSOA, @NOME, @EMPRESA,
    {{ Number($json.CGPESSOA_ESTADO || 1) }},
    {{ Number($json.CGPESSOA_FISICO_JURIDICO || 2) }},
    {{ Number($json.CGPESSOA_FILIAL || 1) }},
    @DT_ENTRADA, @USUARIO, CONVERT(VARCHAR(20), @PESSOA - 1),
    @DT_ENTRADA, @USUARIO,
    {{ Number($json.CGPESSOA_TIPOEMPRESA || 1) }}
  );
END;

IF EXISTS (
  SELECT 1
  FROM VDNOTAC WITH (UPDLOCK, HOLDLOCK)
  WHERE EMPRESA = @EMPRESA
    AND FILIAL = @FILIAL
    AND ENTRADA_SAIDA = @ENTRADA_SAIDA
    AND PESSOA = @PESSOA
    AND NOTA_FISCAL = @NOTA_FISCAL
    AND ISNULL(SERIE, '') = ISNULL(@SERIE, '')
)
BEGIN
  UPDATE VDNOTAC
  SET
    MOVIMENTACAO_FISCAL = @MOVIMENTACAO_FISCAL,
    DATA_EMISSAO = @DATA_EMISSAO,
    DATA_MOVIMENTACAO = @DT_ENTRADA,
    VALOR_SERVICO = @VALOR_SERVICO,
    VALOR_PRODUTO = 0,
    VALOR_DESCONTO = @VALOR_DESCONTO,
    VALOR_DESCONTO_ITEM = 0,
    VALOR_OUTRAS_DESPESAS = 0,
    VALOR_SEGURO = 0,
    QUANTIDADE_PECAS = 0,
    VALOR_TOTAL = @VALOR_TOTAL,
    VALOR_BASE_ICMS = 0,
    VALOR_ISENTO_ICMS = 0,
    VALOR_OUTROS_ICMS = 0,
    ALIQUOTA_ICMS = 0,
    VALOR_ICMS = 0,
    VALOR_BASE_SUBS_TRIB = 0,
    VALOR_SUBS_TRIB = 0,
    VALOR_BASE_IPI = 0,
    VALOR_IPI = 0,
    VALOR_BASE_ISS = @VALOR_TOTAL,
    VALOR_ISS = @VALOR_ISS,
    ALIQUOTA_ISS = @ALIQUOTA_ISS,
    TIPO_FRETE = {{ Number($json.VDNOTAC_TIPO_FRETE || 1) }},
    VALOR_FRETE = 0,
    FORMA_PGTO = {{ Number($json.VDNOTAC_FORMA_PGTO || 1) }},
    PESO_BRUTO = 0,
    PESO_LIQUIDO = 0,
    DATA_ALTERACAO = @DT_ENTRADA,
    USUARIO_ALTERACAO = @USUARIO,
    MUNICIPIO = @MUNICIPIO,
    UF = @UF,
    CNPJ = @CNPJ,
    NATUREZA = @NATUREZA,
    FLAG_FINANCEIRO = '{{ String($json.VDNOTAC_FLAG_FINANCEIRO || "P").replaceAll("'", "''") }}',
    FLAG_CANCELADO = '{{ String($json.VDNOTAC_FLAG_CANCELADO || "N").replaceAll("'", "''") }}',
    PEDIDO = {{ $json.VDNOTAC_PEDIDO === null || $json.VDNOTAC_PEDIDO === undefined || $json.VDNOTAC_PEDIDO === "" ? "0" : Number($json.VDNOTAC_PEDIDO) }},
    NOMEPESSOA = @NOME,
    OBSERVACAO = @OBSERVACAO,
    DADOS_ADICIONAIS = @DADOS_ADICIONAIS,
    CODIGOMUNICIPIO = @CODIGO_MUNICIPIO,
    CODIGOACESSO = @CODIGO_ACESSO,
    FLAGFRETEINCLUIVALORTOTAL = {{ Number($json.VDNOTAC_FLAGFRETEINCLUIVALORTOTAL || 0) }},
    ModeloDocumento = @MODELO_DOCUMENTO,
    ValorTotalTributacao = 0,
    FlagPerfilPessoa = {{ Number($json.VDNOTAC_FLAGPERFILPESSOA || 1) }},
    FlagIndicadorPresenca = {{ Number($json.VDNOTAC_FLAGINDICADORPRESENCA || 9) }},
    TipoInscricaoEstadual = {{ Number($json.VDNOTAC_TIPOINSCRICAOESTADUAL || 9) }},
    MunicipioOrigem = {{ Number($json.VDNOTAC_MUNICIPIOORIGEM || 0) }},
    MunicipioDestino = {{ Number($json.VDNOTAC_MUNICIPIODESTINO || 0) }}
  WHERE EMPRESA = @EMPRESA
    AND FILIAL = @FILIAL
    AND ENTRADA_SAIDA = @ENTRADA_SAIDA
    AND PESSOA = @PESSOA
    AND NOTA_FISCAL = @NOTA_FISCAL
    AND ISNULL(SERIE, '') = ISNULL(@SERIE, '');
END
ELSE
BEGIN
  INSERT INTO VDNOTAC (
    EMPRESA, FILIAL, ENTRADA_SAIDA, PESSOA, NOTA_FISCAL, SERIE,
    MOVIMENTACAO_FISCAL, DATA_EMISSAO, DATA_MOVIMENTACAO,
    VALOR_SERVICO, VALOR_PRODUTO, VALOR_DESCONTO, VALOR_DESCONTO_ITEM,
    VALOR_OUTRAS_DESPESAS, VALOR_SEGURO, QUANTIDADE_PECAS, VALOR_TOTAL,
    VALOR_BASE_ICMS, VALOR_ISENTO_ICMS, VALOR_OUTROS_ICMS, ALIQUOTA_ICMS,
    VALOR_ICMS, VALOR_BASE_SUBS_TRIB, VALOR_SUBS_TRIB, VALOR_BASE_IPI,
    VALOR_IPI, VALOR_BASE_ISS, VALOR_ISS, ALIQUOTA_ISS, TIPO_FRETE,
    VALOR_FRETE, FORMA_PGTO, PESO_BRUTO, PESO_LIQUIDO,
    DATA_INCLUSAO, USUARIO_INCLUSAO, DATA_ALTERACAO, USUARIO_ALTERACAO,
    MUNICIPIO, UF, CNPJ, NATUREZA, FLAG_FINANCEIRO, FLAG_CANCELADO,
    PEDIDO, VENDEDOR, NOMEPESSOA, OBSERVACAO, DADOS_ADICIONAIS,
    CODIGOMUNICIPIO, CODIGOACESSO, FLAGFRETEINCLUIVALORTOTAL,
    ModeloDocumento, ValorTotalTributacao, FlagPerfilPessoa,
    FlagIndicadorPresenca, TipoInscricaoEstadual, MunicipioOrigem, MunicipioDestino
  )
  VALUES (
    @EMPRESA, @FILIAL, @ENTRADA_SAIDA, @PESSOA, @NOTA_FISCAL, @SERIE,
    @MOVIMENTACAO_FISCAL, @DATA_EMISSAO, @DT_ENTRADA,
    @VALOR_SERVICO, 0, @VALOR_DESCONTO, 0,
    0, 0, 0, @VALOR_TOTAL,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, @VALOR_TOTAL, @VALOR_ISS, @ALIQUOTA_ISS, {{ Number($json.VDNOTAC_TIPO_FRETE || 1) }},
    0, {{ Number($json.VDNOTAC_FORMA_PGTO || 1) }}, 0, 0,
    @DT_ENTRADA, @USUARIO, @DT_ENTRADA, @USUARIO,
    @MUNICIPIO, @UF, @CNPJ, @NATUREZA, '{{ String($json.VDNOTAC_FLAG_FINANCEIRO || "P").replaceAll("'", "''") }}', '{{ String($json.VDNOTAC_FLAG_CANCELADO || "N").replaceAll("'", "''") }}',
    {{ $json.VDNOTAC_PEDIDO === null || $json.VDNOTAC_PEDIDO === undefined || $json.VDNOTAC_PEDIDO === "" ? "0" : Number($json.VDNOTAC_PEDIDO) }}, {{ Number($json.VDNOTAS_VENDEDOR || -1) }}, @NOME, @OBSERVACAO, @DADOS_ADICIONAIS,
    @CODIGO_MUNICIPIO, @CODIGO_ACESSO, {{ Number($json.VDNOTAC_FLAGFRETEINCLUIVALORTOTAL || 0) }},
    @MODELO_DOCUMENTO, 0, {{ Number($json.VDNOTAC_FLAGPERFILPESSOA || 1) }},
    {{ Number($json.VDNOTAC_FLAGINDICADORPRESENCA || 9) }}, {{ Number($json.VDNOTAC_TIPOINSCRICAOESTADUAL || 9) }}, {{ Number($json.VDNOTAC_MUNICIPIOORIGEM || 0) }}, {{ Number($json.VDNOTAC_MUNICIPIODESTINO || 0) }}
  );
END;

DELETE FROM VDNOTAS
WHERE EMPRESA = @EMPRESA
  AND FILIAL = @FILIAL
  AND ENTRADA_SAIDA = @ENTRADA_SAIDA
  AND PESSOA = @PESSOA
  AND NOTA_FISCAL = @NOTA_FISCAL
  AND ISNULL(SERIE, '') = ISNULL(@SERIE, '')
  AND SEQUENCIA = {{ Number($json.VDNOTAS_SEQUENCIA || 1) }};

INSERT INTO VDNOTAS (
  EMPRESA, FILIAL, ENTRADA_SAIDA, PESSOA, NOTA_FISCAL, SERIE,
  SEQUENCIA, SERVICO, DESCRICAO, QUANTIDADE, VALOR_TOTAL,
  VALOR_DESCONTO, PERC_DESCONTO, ALIQUOTA_ISS, VALOR_ISS,
  VENDEDOR, DATA_INCLUSAO, USUARIO_INCLUSAO, DATA_ALTERACAO,
  USUARIO_ALTERACAO, MOVIMENTACAOFISCAL, ALIQUOTAICMS,
  VALORBASEICMS, VALORICMS, CodigoFederalServico,
  CodigoMunicipioOcorrencia, NaturezaCredito, CSTCOFINS,
  ValorCOFINS, CSTPIS, ValorPIS, ValorTotalTributacao,
  ValorDeducao, CodigoPadrao, DescricaoCompleta, ContaContabil,
  CodigoPadrao2, CSTCBS, BaseCalculoCBS, AliquotaCBS, ValorCBS,
  BaseCalculoIBS, AliquotaIBS, ValorIBS, BaseCalculoIS,
  AliquotaIS, ValorIS, CSTClassificacaoCBS, BaseCalculoIBSMunicipio,
  AliquotaIBSMunicipio, ValorIBSMunicipio, AliquotaIBSIntegral,
  ReducaoAliquotaIBS, AliquotaCBSIntegral, ReducaoAliquotaCBS
)
VALUES (
  @EMPRESA, @FILIAL, @ENTRADA_SAIDA, @PESSOA, @NOTA_FISCAL, @SERIE,
  {{ Number($json.VDNOTAS_SEQUENCIA || 1) }}, @SERVICO, LEFT(@DESCRICAO, 255), 1, @VALOR_TOTAL,
  @VALOR_DESCONTO, 0, @ALIQUOTA_ISS, @VALOR_ISS,
  {{ Number($json.VDNOTAS_VENDEDOR || -1) }}, @DT_ENTRADA, @USUARIO, @DT_ENTRADA,
  @USUARIO, @MOVIMENTACAO_FISCAL, 0,
  0, 0, @CODIGO_FEDERAL_SERVICO,
  @CODIGO_MUNICIPIO_OCORRENCIA, @NATUREZA_CREDITO, @CST_COFINS,
  @VALOR_COFINS, @CST_PIS, @VALOR_PIS, 0,
  @VALOR_DEDUCAO, @CODIGO_PADRAO, @DESCRICAO, @CONTA_CONTABIL,
  @CODIGO_PADRAO2, @CST_CBS, 0, 0, 0,
  0, 0, 0, @VALOR_TOTAL,
  0, 0, @CST_CLASSIFICACAO_CBS, @VALOR_TOTAL,
  0, 0, {{ Number($json.VDNOTAS_ALIQUOTAIBSINTEGRAL || 0.1) }},
  {{ Number($json.VDNOTAS_REDUCAOALIQUOTAIBS || 100) }}, {{ Number($json.VDNOTAS_ALIQUOTACBSINTEGRAL || 0.9) }}, {{ Number($json.VDNOTAS_REDUCAOALIQUOTACBS || 100) }}
);

COMMIT;

SELECT
  {{ Number($json.ID || 0) }} AS ID,
  @PESSOA AS ID_FORNECEDOR,
  @EMPRESA AS DECIS_EMPRESA,
  @FILIAL AS DECIS_FILIAL,
  @ENTRADA_SAIDA AS DECIS_ENTRADA_SAIDA,
  @NOTA_FISCAL AS DECIS_NOTA_FISCAL,
  @SERIE AS DECIS_SERIE,
  CONVERT(VARCHAR(10), @DT_ENTRADA, 120) AS DECIS_DATA_ENTRADA,
  'S' AS IMPORTADO_DECIS,
  'NFSE integrada/atualizada no Decis' AS RESULTADO_DECIS;
