SET XACT_ABORT ON;
SET DATEFORMAT ymd;

DECLARE @EMPRESA INT = {{ $json.VDNOTAC_EMPRESA === null || $json.VDNOTAC_EMPRESA === undefined || $json.VDNOTAC_EMPRESA === "" ? "NULL" : Number($json.VDNOTAC_EMPRESA) }};
DECLARE @FILIAL INT = {{ $json.VDNOTAC_FILIAL === null || $json.VDNOTAC_FILIAL === undefined || $json.VDNOTAC_FILIAL === "" ? "NULL" : Number($json.VDNOTAC_FILIAL) }};
DECLARE @ENTRADA_SAIDA VARCHAR(1) = '{{ String($json.VDNOTAC_ENTRADA_SAIDA || "E").replaceAll("'", "''") }}';
DECLARE @PESSOA INT = NULL;
DECLARE @NOTA_FISCAL NUMERIC(18,0) = {{ $json.VDNOTAC_NOTA_FISCAL === null || $json.VDNOTAC_NOTA_FISCAL === undefined || $json.VDNOTAC_NOTA_FISCAL === "" ? "NULL" : Number(String($json.VDNOTAC_NOTA_FISCAL).replace(/\D/g, '') || 0) }};
DECLARE @SERIE VARCHAR(10) = '{{ String($json.VDNOTAC_SERIE || "E").replaceAll("'", "''") }}';
DECLARE @MOVIMENTACAO_FISCAL INT = {{ $json.VDNOTAC_MOVIMENTACAO_FISCAL === null || $json.VDNOTAC_MOVIMENTACAO_FISCAL === undefined || $json.VDNOTAC_MOVIMENTACAO_FISCAL === "" ? "NULL" : Number($json.VDNOTAC_MOVIMENTACAO_FISCAL) }};
DECLARE @DATA_EMISSAO_TXT VARCHAR(40) = NULLIF('{{ String($json.VDNOTAC_DATA_EMISSAO || "").replaceAll("'", "''") }}', '');
DECLARE @DT_ENTRADA_TXT VARCHAR(40) = NULLIF('{{ String($json.DECIS_DATA_ENTRADA || "").replaceAll("'", "''") }}', '');
DECLARE @DATA_EMISSAO DATETIME;
DECLARE @DT_ENTRADA DATETIME;

IF @DATA_EMISSAO_TXT IS NOT NULL
BEGIN
  IF LEFT(@DATA_EMISSAO_TXT, 10) LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
    SET @DATA_EMISSAO = CONVERT(DATETIME, LEFT(@DATA_EMISSAO_TXT, 10), 120);
  ELSE IF LEFT(@DATA_EMISSAO_TXT, 10) LIKE '[0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9]'
    SET @DATA_EMISSAO = CONVERT(DATETIME, LEFT(@DATA_EMISSAO_TXT, 10), 103);
  ELSE IF ISDATE(@DATA_EMISSAO_TXT) = 1
    SET @DATA_EMISSAO = CONVERT(DATETIME, @DATA_EMISSAO_TXT);
END;

IF @DT_ENTRADA_TXT IS NOT NULL
BEGIN
  IF LEFT(@DT_ENTRADA_TXT, 10) LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
    SET @DT_ENTRADA = CONVERT(DATETIME, LEFT(@DT_ENTRADA_TXT, 10), 120);
  ELSE IF LEFT(@DT_ENTRADA_TXT, 10) LIKE '[0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9]'
    SET @DT_ENTRADA = CONVERT(DATETIME, LEFT(@DT_ENTRADA_TXT, 10), 103);
  ELSE IF ISDATE(@DT_ENTRADA_TXT) = 1
    SET @DT_ENTRADA = CONVERT(DATETIME, @DT_ENTRADA_TXT);
END;
DECLARE @USUARIO INT = {{ $json.VDNOTAC_USUARIO_INCLUSAO === null || $json.VDNOTAC_USUARIO_INCLUSAO === undefined || $json.VDNOTAC_USUARIO_INCLUSAO === "" ? "9980" : Number($json.VDNOTAC_USUARIO_INCLUSAO) }};
DECLARE @CNPJ VARCHAR(20) = '{{ String($json.CNPJ_FORNECEDOR_LIMPO || $json.VDNOTAC_CNPJ || "").replaceAll("'", "''") }}';
DECLARE @NOME VARCHAR(100) = LEFT('{{ String($json.VDNOTAC_NOMEPESSOA || $json.FORNECEDOR || "FORNECEDOR NFS-E").replaceAll("'", "''") }}', 100);
DECLARE @MUNICIPIO VARCHAR(40) = LEFT('{{ String($json.VDNOTAC_MUNICIPIO || $json.CIDADE_FORNECEDOR || "").replaceAll("'", "''") }}', 40);
DECLARE @UF VARCHAR(2) = LEFT('{{ String($json.VDNOTAC_UF || $json.UF_FORNECEDOR || "").replaceAll("'", "''") }}', 2);
DECLARE @CODIGO_MUNICIPIO INT = {{ $json.VDNOTAC_CODIGOMUNICIPIO === null || $json.VDNOTAC_CODIGOMUNICIPIO === undefined || $json.VDNOTAC_CODIGOMUNICIPIO === "" ? "NULL" : Number($json.VDNOTAC_CODIGOMUNICIPIO) }};
DECLARE @ENDERECO VARCHAR(120) = LEFT('{{ String($json.CGPESSOA_ENDERECO || "").replaceAll("'", "''") }}', 120);
DECLARE @NUMEROENDERECO VARCHAR(20) = LEFT('{{ String($json.CGPESSOA_NUMEROENDERECO || "").replaceAll("'", "''") }}', 20);
DECLARE @BAIRRO VARCHAR(40) = LEFT('{{ String($json.CGPESSOA_BAIRRO || "").replaceAll("'", "''") }}', 40);
DECLARE @CEP VARCHAR(10) = LEFT('{{ String($json.CGPESSOA_CEP || "").replaceAll("'", "''") }}', 10);
DECLARE @FONE VARCHAR(20) = LEFT('{{ String($json.CGPESSOA_FONE || "").replaceAll("'", "''") }}', 20);
DECLARE @INSCR_ESTADUAL VARCHAR(20) = LEFT('{{ String($json.CGPESSOA_INSCR_ESTADUAL || "").replaceAll("'", "''") }}', 20);
DECLARE @CODIGO_ACESSO VARCHAR(255) = LEFT('{{ String($json.VDNOTAC_CODIGOACESSO || $json.CHAVE || "").replaceAll("'", "''") }}', 255);
DECLARE @NATUREZA VARCHAR(60) = LEFT('{{ String($json.VDNOTAC_NATUREZA || "Prestacao de Servico").replaceAll("'", "''") }}', 60);
DECLARE @OBSERVACAO VARCHAR(MAX) = '{{ String($json.VDNOTAC_OBSERVACAO || $json.OBSERVACAO || "").replaceAll("'", "''") }}';
DECLARE @DADOS_ADICIONAIS VARCHAR(MAX) = '{{ String($json.VDNOTAC_DADOS_ADICIONAIS || "").replaceAll("'", "''") }}';
DECLARE @DESCRICAO VARCHAR(MAX) = '{{ String($json.VDNOTAS_DESCRICAO || $json.DESCRICAO || "SERVICO NFS-E").replaceAll("'", "''") }}';
DECLARE @MODELO_DOCUMENTO VARCHAR(10) = '{{ String($json.VDNOTAC_MODELODOCUMENTO || "01").replaceAll("'", "''") }}';

DECLARE @VALOR_SERVICO NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_SERVICO || 0) }};
DECLARE @VALOR_TOTAL NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_TOTAL || $json.VALOR || 0) }};
DECLARE @VALOR_DESCONTO NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_DESCONTO || 0) }};
DECLARE @VALOR_ISS NUMERIC(15,2) = {{ Number($json.VDNOTAC_VALOR_ISS || 0) }};
DECLARE @ALIQUOTA_ISS NUMERIC(15,4) = {{ Number($json.VDNOTAC_ALIQUOTA_ISS || 0) }};
DECLARE @VALOR_PIS NUMERIC(15,2) = {{ Number($json.VDNOTAS_VALORPIS || 0) }};
DECLARE @VALOR_COFINS NUMERIC(15,2) = {{ Number($json.VDNOTAS_VALORCOFINS || 0) }};
DECLARE @VALOR_DEDUCAO NUMERIC(15,2) = {{ Number($json.VDNOTAS_VALORDEDUCAO || 0) }};
DECLARE @SERVICO INT = {{ Number($json.VDNOTAS_SERVICO || 0) }};
DECLARE @CODIGO_FEDERAL_SERVICO INT = {{ $json.VDNOTAS_CODIGOFEDERALSERVICO === null || $json.VDNOTAS_CODIGOFEDERALSERVICO === undefined || $json.VDNOTAS_CODIGOFEDERALSERVICO === "" ? "NULL" : Number($json.VDNOTAS_CODIGOFEDERALSERVICO) }};
DECLARE @CODIGO_MUNICIPIO_OCORRENCIA INT = {{ $json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA === null || $json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA === undefined || $json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA === "" ? "NULL" : Number($json.VDNOTAS_CODIGOMUNICIPIOOCORRENCIA) }};
DECLARE @NATUREZA_CREDITO INT = {{ Number($json.VDNOTAS_NATUREZACREDITO || 3) }};
DECLARE @CST_COFINS INT = {{ Number($json.VDNOTAS_CSTCOFINS || 74) }};
DECLARE @CST_PIS INT = {{ Number($json.VDNOTAS_CSTPIS || 74) }};
DECLARE @CODIGO_PADRAO INT = {{ $json.VDNOTAS_CODIGOPADRAO === null || $json.VDNOTAS_CODIGOPADRAO === undefined || $json.VDNOTAS_CODIGOPADRAO === "" ? "NULL" : Number($json.VDNOTAS_CODIGOPADRAO) }};
DECLARE @CONTA_CONTABIL INT = {{ $json.VDNOTAS_CONTACONTABIL === null || $json.VDNOTAS_CONTACONTABIL === undefined || $json.VDNOTAS_CONTACONTABIL === "" ? "NULL" : Number($json.VDNOTAS_CONTACONTABIL) }};
DECLARE @CODIGO_PADRAO2 INT = {{ Number($json.VDNOTAS_CODIGOPADRAO2 || 410) }};
DECLARE @CST_CBS INT = {{ Number($json.VDNOTAS_CSTCBS || 410) }};
DECLARE @CST_CLASSIFICACAO_CBS INT = {{ Number($json.VDNOTAS_CSTCLASSIFICACAOCBS || 410999) }};

IF @EMPRESA IS NULL THROW 51000, 'EMPRESA DECIS nao informada.', 1;
IF @FILIAL IS NULL THROW 51001, 'FILIAL DECIS nao localizada pelo CNPJ da empresa. Verifique o CASE de filial na consulta do Hub.', 1;
IF @NOTA_FISCAL IS NULL THROW 51002, 'NUMERO DA NOTA nao informado.', 1;
IF @MOVIMENTACAO_FISCAL IS NULL THROW 51003, 'MOVIMENTACAO FISCAL / CFOP nao informado.', 1;
IF @DT_ENTRADA IS NULL THROW 51004, 'DATA DE ENTRADA DECIS nao informada.', 1;
IF @CNPJ = '' THROW 51005, 'CNPJ DO FORNECEDOR nao informado.', 1;

BEGIN TRAN;

DECLARE @DOCUMENTO_COL SYSNAME;
DECLARE @SQL NVARCHAR(MAX);

SELECT TOP 1 @DOCUMENTO_COL = name
FROM sys.columns
WHERE object_id = OBJECT_ID('CGPESSOA')
  AND UPPER(name) IN ('CNPJ', 'CPF_CNPJ', 'CPFCNPJ', 'CNPJCPF', 'CNPJ_CPF', 'DOCUMENTO', 'CGC', 'CGCCPF', 'CNPF')
ORDER BY CASE UPPER(name)
    WHEN 'CNPJ' THEN 1
    WHEN 'CPF_CNPJ' THEN 2
    WHEN 'CPFCNPJ' THEN 3
    WHEN 'CNPJCPF' THEN 4
    WHEN 'CNPJ_CPF' THEN 5
    WHEN 'DOCUMENTO' THEN 6
    ELSE 9
END;

IF @DOCUMENTO_COL IS NOT NULL
BEGIN
  SET @SQL = N'
    SELECT TOP 1 @PESSOA_OUT = PESSOA
    FROM CGPESSOA WITH (UPDLOCK, HOLDLOCK)
    WHERE REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CONVERT(VARCHAR(30), ' + QUOTENAME(@DOCUMENTO_COL) + N'), ''''), ''.'', ''''), ''/'', ''''), ''-'', ''''), '' '', '''') = @CNPJ_IN
      AND ISNULL(PESSOA, 0) > 0
    ORDER BY PESSOA';
  EXEC sp_executesql @SQL, N'@CNPJ_IN VARCHAR(20), @PESSOA_OUT INT OUTPUT', @CNPJ_IN = @CNPJ, @PESSOA_OUT = @PESSOA OUTPUT;
END;

IF @PESSOA IS NULL
BEGIN
  SELECT TOP 1 @PESSOA = PESSOA
  FROM VDNOTAC WITH (UPDLOCK, HOLDLOCK)
  WHERE REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CNPJ, ''), '.', ''), '/', ''), '-', ''), ' ', '') = @CNPJ
    AND ISNULL(PESSOA, 0) > 0
  ORDER BY DATA_MOVIMENTACAO DESC, DATA_INCLUSAO DESC, PESSOA DESC;
END;

IF @PESSOA IS NULL
BEGIN
  SELECT @PESSOA = ISNULL(MAX(PESSOA), 0) + 1
  FROM CGPESSOA WITH (UPDLOCK, HOLDLOCK);

  INSERT INTO CGPESSOA (
    PESSOA, NOME, EMPRESA, ESTADO, FISICO_JURIDICO, FILIAL,
    DATA_ALTERACAO, USUARIO_ALTERACAO, SENHA, DataHoraInclusao,
    UsuarioInclusao, TipoEmpresa
  )
  VALUES (
    @PESSOA, @NOME, @EMPRESA,
    {{ Number($json.CGPESSOA_ESTADO || 1) }},
    {{ Number($json.CGPESSOA_FISICO_JURIDICO || 2) }},
    {{ Number($json.CGPESSOA_FILIAL || 1) }},
    @DT_ENTRADA, @USUARIO, CONVERT(VARCHAR(20), @PESSOA - 1),
    @DT_ENTRADA, @USUARIO,
    {{ Number($json.CGPESSOA_TIPOEMPRESA || 1) }}
  );
END;

CREATE TABLE #CADASTRO_FORNECEDOR_DECIS (
  NOME VARCHAR(100) NULL,
  ENDERECO VARCHAR(120) NULL,
  NUMEROENDERECO VARCHAR(20) NULL,
  BAIRRO VARCHAR(40) NULL,
  CEP VARCHAR(10) NULL,
  MUNICIPIO VARCHAR(40) NULL,
  FONE VARCHAR(20) NULL,
  UF VARCHAR(2) NULL,
  INSCR_ESTADUAL VARCHAR(20) NULL,
  CODIGOMUNICIPIO INT NULL
);

IF OBJECT_ID('CGPESSOA') IS NOT NULL
BEGIN
  SET @SQL = N'INSERT INTO #CADASTRO_FORNECEDOR_DECIS (NOME, ENDERECO, NUMEROENDERECO, BAIRRO, CEP, MUNICIPIO, FONE, UF, INSCR_ESTADUAL, CODIGOMUNICIPIO)
    SELECT TOP 1 ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'NOME') IS NOT NULL THEN N'CONVERT(VARCHAR(100), NOME)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'ENDERECO') IS NOT NULL THEN N'CONVERT(VARCHAR(120), ENDERECO)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'NUMEROENDERECO') IS NOT NULL THEN N'CONVERT(VARCHAR(20), NUMEROENDERECO)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'BAIRRO') IS NOT NULL THEN N'CONVERT(VARCHAR(40), BAIRRO)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'CEP') IS NOT NULL THEN N'CONVERT(VARCHAR(10), CEP)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'MUNICIPIO') IS NOT NULL THEN N'CONVERT(VARCHAR(40), MUNICIPIO)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'FONE') IS NOT NULL THEN N'CONVERT(VARCHAR(20), FONE)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'UF') IS NOT NULL THEN N'CONVERT(VARCHAR(2), UF)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'INSCR_ESTADUAL') IS NOT NULL THEN N'CONVERT(VARCHAR(20), INSCR_ESTADUAL)' ELSE N'NULL' END + N', ' +
    CASE WHEN COL_LENGTH('CGPESSOA', 'CODIGOMUNICIPIO') IS NOT NULL THEN N'TRY_CONVERT(INT, CODIGOMUNICIPIO)' ELSE N'NULL' END + N'
    FROM CGPESSOA WITH (NOLOCK)
    WHERE PESSOA = @PESSOA_IN
    ORDER BY PESSOA';
  EXEC sp_executesql @SQL, N'@PESSOA_IN INT', @PESSOA_IN = @PESSOA;
END;

IF NOT EXISTS (SELECT 1 FROM #CADASTRO_FORNECEDOR_DECIS)
BEGIN
  INSERT INTO #CADASTRO_FORNECEDOR_DECIS (NOME, ENDERECO, NUMEROENDERECO, BAIRRO, CEP, MUNICIPIO, FONE, UF, INSCR_ESTADUAL, CODIGOMUNICIPIO)
  SELECT TOP 1 NOMEPESSOA, ENDERECO, CONVERT(VARCHAR(20), NUMEROENDERECO), BAIRRO, CEP, MUNICIPIO, FONE, UF, INSCR_ESTADUAL, CODIGOMUNICIPIO
  FROM VDNOTAC WITH (NOLOCK)
  WHERE PESSOA = @PESSOA
     OR REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CNPJ, ''), '.', ''), '/', ''), '-', ''), ' ', '') = @CNPJ
  ORDER BY DATA_MOVIMENTACAO DESC, DATA_INCLUSAO DESC;
END;

SELECT TOP 1
  @NOME = LEFT(COALESCE(NULLIF(@NOME, ''), NULLIF(NOME, '')), 100),
  @ENDERECO = LEFT(COALESCE(NULLIF(@ENDERECO, ''), NULLIF(ENDERECO, '')), 120),
  @NUMEROENDERECO = LEFT(COALESCE(NULLIF(@NUMEROENDERECO, ''), NULLIF(NUMEROENDERECO, '')), 20),
  @BAIRRO = LEFT(COALESCE(NULLIF(@BAIRRO, ''), NULLIF(BAIRRO, '')), 40),
  @CEP = LEFT(COALESCE(NULLIF(@CEP, ''), NULLIF(CEP, '')), 10),
  @MUNICIPIO = LEFT(COALESCE(NULLIF(@MUNICIPIO, ''), NULLIF(MUNICIPIO, '')), 40),
  @FONE = LEFT(COALESCE(NULLIF(@FONE, ''), NULLIF(FONE, '')), 20),
  @UF = LEFT(COALESCE(NULLIF(@UF, ''), NULLIF(UF, '')), 2),
  @INSCR_ESTADUAL = LEFT(COALESCE(NULLIF(@INSCR_ESTADUAL, ''), NULLIF(INSCR_ESTADUAL, '')), 20),
  @CODIGO_MUNICIPIO = COALESCE(@CODIGO_MUNICIPIO, CODIGOMUNICIPIO)
FROM #CADASTRO_FORNECEDOR_DECIS;

DECLARE @UPDATE_CGPESSOA_SET NVARCHAR(MAX) = N'';
IF COL_LENGTH('CGPESSOA', 'NOME') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', NOME = COALESCE(NULLIF(@NOME_IN, ''''), NOME)';
IF @DOCUMENTO_COL IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', ' + QUOTENAME(@DOCUMENTO_COL) + N' = COALESCE(NULLIF(@CNPJ_IN, ''''), ' + QUOTENAME(@DOCUMENTO_COL) + N')';
IF COL_LENGTH('CGPESSOA', 'ENDERECO') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', ENDERECO = COALESCE(NULLIF(@ENDERECO_IN, ''''), ENDERECO)';
IF COL_LENGTH('CGPESSOA', 'NUMEROENDERECO') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', NUMEROENDERECO = COALESCE(NULLIF(@NUMEROENDERECO_IN, ''''), NUMEROENDERECO)';
IF COL_LENGTH('CGPESSOA', 'BAIRRO') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', BAIRRO = COALESCE(NULLIF(@BAIRRO_IN, ''''), BAIRRO)';
IF COL_LENGTH('CGPESSOA', 'CEP') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', CEP = COALESCE(NULLIF(@CEP_IN, ''''), CEP)';
IF COL_LENGTH('CGPESSOA', 'MUNICIPIO') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', MUNICIPIO = COALESCE(NULLIF(@MUNICIPIO_IN, ''''), MUNICIPIO)';
IF COL_LENGTH('CGPESSOA', 'FONE') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', FONE = COALESCE(NULLIF(@FONE_IN, ''''), FONE)';
IF COL_LENGTH('CGPESSOA', 'UF') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', UF = COALESCE(NULLIF(@UF_IN, ''''), UF)';
IF COL_LENGTH('CGPESSOA', 'INSCR_ESTADUAL') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', INSCR_ESTADUAL = COALESCE(NULLIF(@INSCR_ESTADUAL_IN, ''''), INSCR_ESTADUAL)';
IF COL_LENGTH('CGPESSOA', 'CODIGOMUNICIPIO') IS NOT NULL SET @UPDATE_CGPESSOA_SET += N', CODIGOMUNICIPIO = COALESCE(@CODIGO_MUNICIPIO_IN, CODIGOMUNICIPIO)';

IF @UPDATE_CGPESSOA_SET <> N''
BEGIN
  SET @SQL = N'UPDATE CGPESSOA SET ' + STUFF(@UPDATE_CGPESSOA_SET, 1, 2, N'') + N' WHERE PESSOA = @PESSOA_IN';
  EXEC sp_executesql @SQL,
    N'@PESSOA_IN INT, @CNPJ_IN VARCHAR(20), @NOME_IN VARCHAR(100), @ENDERECO_IN VARCHAR(120), @NUMEROENDERECO_IN VARCHAR(20), @BAIRRO_IN VARCHAR(40), @CEP_IN VARCHAR(10), @MUNICIPIO_IN VARCHAR(40), @FONE_IN VARCHAR(20), @UF_IN VARCHAR(2), @INSCR_ESTADUAL_IN VARCHAR(20), @CODIGO_MUNICIPIO_IN INT',
    @PESSOA_IN = @PESSOA,
    @CNPJ_IN = @CNPJ,
    @NOME_IN = @NOME,
    @ENDERECO_IN = @ENDERECO,
    @NUMEROENDERECO_IN = @NUMEROENDERECO,
    @BAIRRO_IN = @BAIRRO,
    @CEP_IN = @CEP,
    @MUNICIPIO_IN = @MUNICIPIO,
    @FONE_IN = @FONE,
    @UF_IN = @UF,
    @INSCR_ESTADUAL_IN = @INSCR_ESTADUAL,
    @CODIGO_MUNICIPIO_IN = @CODIGO_MUNICIPIO;
END;

IF EXISTS (
  SELECT 1
  FROM VDNOTAC WITH (UPDLOCK, HOLDLOCK)
  WHERE EMPRESA = @EMPRESA
    AND FILIAL = @FILIAL
    AND ENTRADA_SAIDA = @ENTRADA_SAIDA
    AND PESSOA = @PESSOA
    AND NOTA_FISCAL = @NOTA_FISCAL
    AND ISNULL(SERIE, '') = ISNULL(@SERIE, '')
)
BEGIN
  UPDATE VDNOTAC
  SET
    MOVIMENTACAO_FISCAL = @MOVIMENTACAO_FISCAL,
    DATA_EMISSAO = @DATA_EMISSAO,
    DATA_MOVIMENTACAO = @DT_ENTRADA,
    VALOR_SERVICO = @VALOR_SERVICO,
    VALOR_PRODUTO = 0,
    VALOR_DESCONTO = @VALOR_DESCONTO,
    VALOR_DESCONTO_ITEM = 0,
    VALOR_OUTRAS_DESPESAS = 0,
    VALOR_SEGURO = 0,
    QUANTIDADE_PECAS = 0,
    VALOR_TOTAL = @VALOR_TOTAL,
    VALOR_BASE_ICMS = 0,
    VALOR_ISENTO_ICMS = 0,
    VALOR_OUTROS_ICMS = 0,
    ALIQUOTA_ICMS = 0,
    VALOR_ICMS = 0,
    VALOR_BASE_SUBS_TRIB = 0,
    VALOR_SUBS_TRIB = 0,
    VALOR_BASE_IPI = 0,
    VALOR_IPI = 0,
    VALOR_BASE_ISS = @VALOR_TOTAL,
    VALOR_ISS = @VALOR_ISS,
    ALIQUOTA_ISS = @ALIQUOTA_ISS,
    TIPO_FRETE = {{ Number($json.VDNOTAC_TIPO_FRETE || 1) }},
    VALOR_FRETE = 0,
    FORMA_PGTO = {{ Number($json.VDNOTAC_FORMA_PGTO || 1) }},
    PESO_BRUTO = 0,
    PESO_LIQUIDO = 0,
    DATA_ALTERACAO = @DT_ENTRADA,
    USUARIO_ALTERACAO = @USUARIO,
    MUNICIPIO = @MUNICIPIO,
    BAIRRO = @BAIRRO,
    CEP = @CEP,
    FONE = @FONE,
    UF = @UF,
    CNPJ = @CNPJ,
    INSCR_ESTADUAL = @INSCR_ESTADUAL,
    NATUREZA = @NATUREZA,
    FLAG_FINANCEIRO = '{{ String($json.VDNOTAC_FLAG_FINANCEIRO || "P").replaceAll("'", "''") }}',
    FLAG_CANCELADO = '{{ String($json.VDNOTAC_FLAG_CANCELADO || "N").replaceAll("'", "''") }}',
    PEDIDO = {{ $json.VDNOTAC_PEDIDO === null || $json.VDNOTAC_PEDIDO === undefined || $json.VDNOTAC_PEDIDO === "" ? "0" : Number($json.VDNOTAC_PEDIDO) }},
    NOMEPESSOA = @NOME,
    OBSERVACAO = @OBSERVACAO,
    DADOS_ADICIONAIS = @DADOS_ADICIONAIS,
    CODIGOMUNICIPIO = @CODIGO_MUNICIPIO,
    CODIGOACESSO = @CODIGO_ACESSO,
    ENDERECO = @ENDERECO,
    NUMEROENDERECO = @NUMEROENDERECO,
    FLAGFRETEINCLUIVALORTOTAL = {{ Number($json.VDNOTAC_FLAGFRETEINCLUIVALORTOTAL || 0) }},
    ModeloDocumento = @MODELO_DOCUMENTO,
    ValorTotalTributacao = 0,
    FlagPerfilPessoa = {{ Number($json.VDNOTAC_FLAGPERFILPESSOA || 1) }},
    FlagIndicadorPresenca = {{ Number($json.VDNOTAC_FLAGINDICADORPRESENCA || 9) }},
    TipoInscricaoEstadual = {{ Number($json.VDNOTAC_TIPOINSCRICAOESTADUAL || 9) }},
    MunicipioOrigem = {{ Number($json.VDNOTAC_MUNICIPIOORIGEM || 0) }},
    MunicipioDestino = {{ Number($json.VDNOTAC_MUNICIPIODESTINO || 0) }}
  WHERE EMPRESA = @EMPRESA
    AND FILIAL = @FILIAL
    AND ENTRADA_SAIDA = @ENTRADA_SAIDA
    AND PESSOA = @PESSOA
    AND NOTA_FISCAL = @NOTA_FISCAL
    AND ISNULL(SERIE, '') = ISNULL(@SERIE, '');
END
ELSE
BEGIN
  INSERT INTO VDNOTAC (
    EMPRESA, FILIAL, ENTRADA_SAIDA, PESSOA, NOTA_FISCAL, SERIE,
    MOVIMENTACAO_FISCAL, DATA_EMISSAO, DATA_MOVIMENTACAO,
    VALOR_SERVICO, VALOR_PRODUTO, VALOR_DESCONTO, VALOR_DESCONTO_ITEM,
    VALOR_OUTRAS_DESPESAS, VALOR_SEGURO, QUANTIDADE_PECAS, VALOR_TOTAL,
    VALOR_BASE_ICMS, VALOR_ISENTO_ICMS, VALOR_OUTROS_ICMS, ALIQUOTA_ICMS,
    VALOR_ICMS, VALOR_BASE_SUBS_TRIB, VALOR_SUBS_TRIB, VALOR_BASE_IPI,
    VALOR_IPI, VALOR_BASE_ISS, VALOR_ISS, ALIQUOTA_ISS, TIPO_FRETE,
    VALOR_FRETE, FORMA_PGTO, PESO_BRUTO, PESO_LIQUIDO,
    DATA_INCLUSAO, USUARIO_INCLUSAO, DATA_ALTERACAO, USUARIO_ALTERACAO,
    BAIRRO, CEP, MUNICIPIO, FONE, UF, CNPJ, NATUREZA, INSCR_ESTADUAL, FLAG_FINANCEIRO, FLAG_CANCELADO,
    PEDIDO, VENDEDOR, NOMEPESSOA, OBSERVACAO, DADOS_ADICIONAIS,
    CODIGOMUNICIPIO, CODIGOACESSO, FLAGFRETEINCLUIVALORTOTAL,
    ENDERECO, NUMEROENDERECO,
    ModeloDocumento, ValorTotalTributacao, FlagPerfilPessoa,
    FlagIndicadorPresenca, TipoInscricaoEstadual, MunicipioOrigem, MunicipioDestino
  )
  VALUES (
    @EMPRESA, @FILIAL, @ENTRADA_SAIDA, @PESSOA, @NOTA_FISCAL, @SERIE,
    @MOVIMENTACAO_FISCAL, @DATA_EMISSAO, @DT_ENTRADA,
    @VALOR_SERVICO, 0, @VALOR_DESCONTO, 0,
    0, 0, 0, @VALOR_TOTAL,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, @VALOR_TOTAL, @VALOR_ISS, @ALIQUOTA_ISS, {{ Number($json.VDNOTAC_TIPO_FRETE || 1) }},
    0, {{ Number($json.VDNOTAC_FORMA_PGTO || 1) }}, 0, 0,
    @DT_ENTRADA, @USUARIO, @DT_ENTRADA, @USUARIO,
    @BAIRRO, @CEP, @MUNICIPIO, @FONE, @UF, @CNPJ, @NATUREZA, @INSCR_ESTADUAL, '{{ String($json.VDNOTAC_FLAG_FINANCEIRO || "P").replaceAll("'", "''") }}', '{{ String($json.VDNOTAC_FLAG_CANCELADO || "N").replaceAll("'", "''") }}',
    {{ $json.VDNOTAC_PEDIDO === null || $json.VDNOTAC_PEDIDO === undefined || $json.VDNOTAC_PEDIDO === "" ? "0" : Number($json.VDNOTAC_PEDIDO) }}, {{ Number($json.VDNOTAS_VENDEDOR || -1) }}, @NOME, @OBSERVACAO, @DADOS_ADICIONAIS,
    @CODIGO_MUNICIPIO, @CODIGO_ACESSO, {{ Number($json.VDNOTAC_FLAGFRETEINCLUIVALORTOTAL || 0) }},
    @ENDERECO, @NUMEROENDERECO,
    @MODELO_DOCUMENTO, 0, {{ Number($json.VDNOTAC_FLAGPERFILPESSOA || 1) }},
    {{ Number($json.VDNOTAC_FLAGINDICADORPRESENCA || 9) }}, {{ Number($json.VDNOTAC_TIPOINSCRICAOESTADUAL || 9) }}, {{ Number($json.VDNOTAC_MUNICIPIOORIGEM || 0) }}, {{ Number($json.VDNOTAC_MUNICIPIODESTINO || 0) }}
  );
END;

DELETE FROM VDNOTAS
WHERE EMPRESA = @EMPRESA
  AND FILIAL = @FILIAL
  AND ENTRADA_SAIDA = @ENTRADA_SAIDA
  AND PESSOA = @PESSOA
  AND NOTA_FISCAL = @NOTA_FISCAL
  AND ISNULL(SERIE, '') = ISNULL(@SERIE, '')
  AND SEQUENCIA = {{ Number($json.VDNOTAS_SEQUENCIA || 1) }};

INSERT INTO VDNOTAS (
  EMPRESA, FILIAL, ENTRADA_SAIDA, PESSOA, NOTA_FISCAL, SERIE,
  SEQUENCIA, SERVICO, DESCRICAO, QUANTIDADE, VALOR_TOTAL,
  VALOR_DESCONTO, PERC_DESCONTO, ALIQUOTA_ISS, VALOR_ISS,
  VENDEDOR, DATA_INCLUSAO, USUARIO_INCLUSAO, DATA_ALTERACAO,
  USUARIO_ALTERACAO, MOVIMENTACAOFISCAL, ALIQUOTAICMS,
  VALORBASEICMS, VALORICMS, CodigoFederalServico,
  CodigoMunicipioOcorrencia, NaturezaCredito, CSTCOFINS,
  ValorCOFINS, CSTPIS, ValorPIS, ValorTotalTributacao,
  ValorDeducao, CodigoPadrao, DescricaoCompleta, ContaContabil,
  CodigoPadrao2, CSTCBS, BaseCalculoCBS, AliquotaCBS, ValorCBS,
  BaseCalculoIBS, AliquotaIBS, ValorIBS, BaseCalculoIS,
  AliquotaIS, ValorIS, CSTClassificacaoCBS, BaseCalculoIBSMunicipio,
  AliquotaIBSMunicipio, ValorIBSMunicipio, AliquotaIBSIntegral,
  ReducaoAliquotaIBS, AliquotaCBSIntegral, ReducaoAliquotaCBS
)
VALUES (
  @EMPRESA, @FILIAL, @ENTRADA_SAIDA, @PESSOA, @NOTA_FISCAL, @SERIE,
  {{ Number($json.VDNOTAS_SEQUENCIA || 1) }}, @SERVICO, LEFT(@DESCRICAO, 255), 1, @VALOR_TOTAL,
  @VALOR_DESCONTO, 0, @ALIQUOTA_ISS, @VALOR_ISS,
  {{ Number($json.VDNOTAS_VENDEDOR || -1) }}, @DT_ENTRADA, @USUARIO, @DT_ENTRADA,
  @USUARIO, @MOVIMENTACAO_FISCAL, 0,
  0, 0, @CODIGO_FEDERAL_SERVICO,
  @CODIGO_MUNICIPIO_OCORRENCIA, @NATUREZA_CREDITO, @CST_COFINS,
  @VALOR_COFINS, @CST_PIS, @VALOR_PIS, 0,
  @VALOR_DEDUCAO, @CODIGO_PADRAO, @DESCRICAO, @CONTA_CONTABIL,
  @CODIGO_PADRAO2, @CST_CBS, 0, 0, 0,
  0, 0, 0, @VALOR_TOTAL,
  0, 0, @CST_CLASSIFICACAO_CBS, @VALOR_TOTAL,
  0, 0, {{ Number($json.VDNOTAS_ALIQUOTAIBSINTEGRAL || 0.1) }},
  {{ Number($json.VDNOTAS_REDUCAOALIQUOTAIBS || 100) }}, {{ Number($json.VDNOTAS_ALIQUOTACBSINTEGRAL || 0.9) }}, {{ Number($json.VDNOTAS_REDUCAOALIQUOTACBS || 100) }}
);

COMMIT;

SELECT
  {{ Number($json.ID || 0) }} AS ID,
  @PESSOA AS ID_FORNECEDOR,
  @EMPRESA AS DECIS_EMPRESA,
  @FILIAL AS DECIS_FILIAL,
  @ENTRADA_SAIDA AS DECIS_ENTRADA_SAIDA,
  @NOTA_FISCAL AS DECIS_NOTA_FISCAL,
  @SERIE AS DECIS_SERIE,
  CONVERT(VARCHAR(10), @DT_ENTRADA, 120) AS DECIS_DATA_ENTRADA,
  'S' AS IMPORTADO_DECIS,
  'NFSE integrada/atualizada no Decis' AS RESULTADO_DECIS;
